DROP TABLE IF EXISTS RESERVATION
DROP TABLE IF EXISTS GUEST
DROP TABLE IF EXISTS ROOM
CREATE TABLE IF NOT EXISTS GUEST(ID int not null AUTO_INCREMENT PRIMARY KEY, FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255), EMAIL VARCHAR(255), PHONE VARCHAR(255))
CREATE TABLE IF NOT EXISTS ROOM(ID int not null PRIMARY KEY, PRICE float not null, BEDS int not null default 1, AIR_CONDITIONING boolean default false, SEA_VIEW boolean default false, FRIDGE boolean default false)
CREATE TABLE IF NOT EXISTS RESERVATION(ID int not null AUTO_INCREMENT PRIMARY KEY, GUEST_ID int, ROOM_ID int, FOREIGN KEY(GUEST_ID) REFERENCES GUEST(ID), FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ID), START_DATE date not null, END_DATE date not null)

INSERT INTO ROOM VALUES (1, 100.0, 1, false, false, false)
INSERT INTO ROOM VALUES (2, 200.0, 1, false, false, false)
INSERT INTO ROOM VALUES (3, 100.0, 1, true, true, true)
INSERT INTO ROOM VALUES (4, 200.0, 1, true, true, true)

INSERT INTO GUEST VALUES(1000, 'Jacek', 'Kowalski', 'test@test.pl', '1111111')
INSERT INTO RESERVATION VALUES(1000, 1000, 4, '2021-02-13', '2021-02-15')